### ISSUE TITLE
Re-add purgeRequireCache

### ISSUE THREAD

**Issue by MoSattler** [MoSattler/repay#2]
Right now we're using nodemon for the server, which works fine. But for faster server side HMR we should exclude the server from nodemon and re-add it. 

Read more about it here: https://github.com/MoSattler/repay/blob/main/server.ts#L93-L97

**Comment by xHomu** [comment]
Make the change when the new Remix dev server becomes stable?

https://github.com/remix-run/remix/releases/tag/remix%401.12.0

**Comment by mooxl** [comment]
Thanks for the nice template! Hasn't the new dev server landed in 1.14 so we can re-add `purgeRequiredCache`?

**Comment by xHomu** [comment]
I haven't had any luck with getting the new dev server to work due to `ts-node` `server.ts`. 

Please share if you managed to get them to play nice together!
